export const  REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const  REGISTER_FAIL = 'REGISTER_FAIL';
export const  LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const  LOGIN_FAIL = 'LOGIN_FAIL';
export const  SUCCESS_MESSAGE_CLEAR = 'SUCCESS_MESSAGE_CLEAR';
export const  ERROR_MESSAGE_CLEAR = 'ERROR_MESSAGE_CLEAR';