export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';   
export const GET_FRIENDS_ERROR = 'GET_FRIENDS_ERROR'; 
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGE_ERROR = 'GET_MESSAGE_ERROR';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const  SEND_MESSAGE_SUCCESS_CLEAR = 'SEND_MESSAGE_SUCCESS_CLEAR';